//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAnd_AccountingOfEquipment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Equipment_accountingEntities : DbContext
    {
        private static Equipment_accountingEntities _context;
        public Equipment_accountingEntities()
            : base("name=Equipment_accountingEntities")
        {
        }
        public static Equipment_accountingEntities GetContext()
        {
            if (_context == null)
                _context = new Equipment_accountingEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Name_Equipment> Name_Equipment { get; set; }
    }
}
